### ISSUE TITLE
binary() function is not exported by ntheory

### ISSUE THREAD

**Issue by trizen** [danaj/Math-Prime-Util#15]
Considering the following code:

``` perl
use 5.010;
use ntheory qw(binary);
say binary(42);
```

it dies with the following error:

```
"binary" is not exported by the ntheory module
Can't continue after import errors at y.pl line 2.
BEGIN failed--compilation aborted at y.pl line 2.
```

Installed version of ntheory is: 0.57.

**Comment by danaj** [comment]
Nice find.  Looks like it was added on Dec 17 and removed the next day (replaced with todigits, todigitstring, fromdigits) but the documentation got left in.
