### ISSUE TITLE
Issue in factor() with Math::GMP

### ISSUE THREAD

**Issue by trizen** [danaj/Math-Prime-Util#20]
Hi Dana Jacobsen,

There seems to be a minor issue in `factor()` when the argument is a Math::GMP object with a value in the range 2^63 up to 2^64 - 1.

```perl
use 5.014;
use warnings;

use Math::GMP;
use ntheory qw(:all);

my $n = Math::GMP->new('9223372036854775818');      # 2^63 + 10
my $v = vecprod(factor($n));

if ($v != $n) {
    say "error: $v != $n";
}

say join(' * ', factor($n));
```

Output:
```
error: 10 != 9223372036854775818
2 * 5
```

As far as I tested, this only happens with Math::GMP.

**Comment by danaj** [comment]
Thanks.  I suspect it's due to https://rt.cpan.org/Ticket/Display.html?id=92564 in Math::GMP, where that module has a messed up intify().

**Comment by danaj** [comment]
For a function given an SV *s, calling SvUV(s) returns the wrong value with Math::GMP.  This is a problem with that module.

The easy but horrible work-around in ntheory is to treat every Math::GMP object as a bignum.  Better would be to identify just these cases.  Best would be to fix Math::GMP.

**Comment by shlomif** [comment]
@trizen : hi! I'm replying here to your private email. @danaj : any chance of seeing the proposed fixes to Math::GMP as a pull request per our agreement in this ticket - https://rt.cpan.org/Public/Bug/Display.html?id=92564 ? I'll be happy to review it, and if I'm happy - merge it and mint a new release.

**Comment by trizen** [comment]
Fixed upstream.
