### ISSUE TITLE
Misaligned version value in ntheory.pm

### ISSUE THREAD

**Issue by emazep** [danaj/Math-Prime-Util#21]
Math/Prime/Util.pm says:

`$Math::Prime::Util::VERSION = '0.60';`

while ntheory.pm says:

`$ntheory::VERSION = '0.59';`

This unfortunately causes `cpanp` (and possibly other tools as well) to insist that ntheory is outdated and should be updated, while it isn't. Sorry to bother you: this is certainly a CPANPLUS problem, but it's probably easier for you to fix.

Thanks!

**Comment by danaj** [comment]
Fixed in 0.61 (and 0.62).  Thanks for report.
