### ISSUE TITLE
Solving (generalised) pell equation

### ISSUE THREAD

**Issue by hvds** [danaj/Math-Prime-Util#30]
It would be useful to have a function that accepts inputs a, b, c (or a, b, c, d, e, f) and returns an iterator yielding integer solutions of `ax^2 + by^2 + c = 0` (respectively: `ax^2 + bxy + cy^2 + dx + ey + f = 0`), with undef to signal no further solutions.

(I acknowledge that I've suggested before that MPU is too large as a single module. :)

I see an existing Haskell solution for a subset at [https://github.com/brunjlar/pell](url), which may be an interesting starting point. The Wolfram page at [http://mathworld.wolfram.com/PellEquation.html](url) also has useful information and a variety of references.

Hugo

**Comment by danaj** [comment]
At the moment this seems like something that should be an application or module.

It's an interesting puzzle, with a lot of info out there.  But I don't think it belongs in the core here.  I've been told Pari/gp has quite a bit of functionality to make solving these fairly easy.
