### ISSUE TITLE
todigitstring("n",b) with very large n, returns NaN

### ISSUE THREAD

**Issue by trizen** [danaj/Math-Prime-Util#32]
Hi @danaj. I was checking if some large numbers (represented as strings in base 10) are palindromic in base 3, and I encountered the following issue:

```perl
use 5.014;
use ntheory qw(:all);

my $n = "7670157375412547872978368814033172196770035110153841376999683462729927501034707760328895032422721536901124858874512783260108363469415109226361490373950895973451430119460927371788894702986500015763331539288960246137094429113278416276220292716408628785636288455875682058237749160041801229006308536730633563187883";
my $s = todigitstring($n, 3);

say $s;                          # not ok (prints "NaN")
say join '', todigits($n, 3);    # ok
```

Passing a large string-number to the function `todigitstring`, seems to return `NaN` for some bases.
However, notice that `todigits` works correctly with the same inputs.

Best regards,
Daniel

**Comment by danaj** [comment]
Thanks!  In this case we went to PP because the input is larger than a native int.  The PP code started doing math on the string without first ensuring it was a bigint. :(

**Comment by trizen** [comment]
Thank you for the fix.
