### ISSUE TITLE
Memory leak in forsquarefree

### ISSUE THREAD

**Issue by trizen** [danaj/Math-Prime-Util#36]
It seems that there are some memory leaks in `forsquarefree` every time the function is called.

The issue can be reproduced with the code below, which starts using more and more RAM.

```perl
use ntheory qw(:all);

for (my $n = 1; ; $n += 1e6) {
    forsquarefree {
        # ...
    } $n, $n+1e6;
}
```

This also seems to happen with the `forfactored` loop.

Other loops, such as `forprimes` or `forcomposites`, do not have this issue.

**Comment by danaj** [comment]
forsquarefree and forfactored were missing a factor_range_destroy call.  Added, with many thanks!

**Comment by trizen** [comment]
Thank you for the fix. Welcome back! :)
