### ISSUE TITLE
[suggestion] Subquadratic algorithm for fromdigits([...], b)

### ISSUE THREAD

**Issue by trizen** [danaj/Math-Prime-Util#37]
In the book [Modern Computer Arithmetic](https://members.loria.fr/PZimmermann/mca/mca-cup-0.5.9.pdf), Richard P. Brent and Paul Zimmermann also present a subquadratic algorithm for conversion of base-b digits to a number (**Algorithm 1.25 FastIntegerInput**), which may be used in `fromdigits([...], b)` to speed things up for large b.

A simple implementation in Perl would be:

```perl
use 5.020;
use strict;
use warnings;

use ntheory qw(fromdigits);
use Math::Prime::Util::GMP qw(todigits factorial mulint addint);

use experimental qw(signatures);

sub FastIntegerInput ($digits, $B) {

    my $L = [reverse @$digits];

    for (my $k = scalar(@$L); $k > 1; $k = ($k>>1) + ($k&1)) {

        my @T;
        for my $i (1 .. $k>>1) {
            my $x = $L->[2*$i-2];
            my $y = $L->[2*$i-1];
            push(@T, addint($x, mulint($B, $y)));
        }
        push(@T, $L->[$k-1]) if ($k&1);
        $L = \@T;
        $B = mulint($B, $B);
    }

    $L->[0] // 0;
}

foreach my $B (2 .. 100) {    # run some tests
    my $N = factorial($B);    # int(rand(~0));

    my @digits = todigits($N, $B);

    my $N_1 = FastIntegerInput(\@digits, $B);
    my $N_2 = fromdigits(\@digits, $B);

    if ($N_1 ne $N_2) {
        die "Error for FastIntegerInput(digits($N), $B): $N_1 != $N_2";
    }
}

use Time::HiRes qw(tv_interval gettimeofday);

my $N = factorial(1e5);
my $B = 100;

my @digits = todigits($N, $B);

my $time = [gettimeofday];

my $N_1 = FastIntegerInput(\@digits, $B);
say "FastIntegerInput() took: ", tv_interval($time), " seconds";

$time = [gettimeofday];

my $N_2 = fromdigits(\@digits, $B);
say "ntheory::fromdigits() took: ", tv_interval($time), " seconds";

if ("$N_1" ne "$N_2") {
    die "error: N_1 != N_2";
}
```

Output:

```
FastIntegerInput() took: 0.888933 seconds
ntheory::fromdigits() took: 13.046574 seconds
```

Perhaps implementing subquadratic `fromdigits([...], b)` in [Math::Prime::Util::GMP](https://github.com/danaj/Math-Prime-Util-GMP) makes more sense (for large b)?

**Comment by danaj** [comment]
Right now base is going to be limited to 2^31 because of the API.  That's arguably an issue.  It makes some sense to make it at least unsigned 2^32.  Going beyond that is possible -- I'm not sure if it's worth the trouble ..... thoughts?

For the GMP function I did:

  base is an uint32_t
  input digits are uint32_t

It would be most flexible to let the input digits be signed bigints.  I'm just not sure how really desirable that feature is.

**Comment by danaj** [comment]
```
$ perl -Iblib/lib -Iblib/arch misc/fromdig.pl 
FastIntegerInput() took: 1.214029 seconds
ntheory::fromdigits() took: 0.149879 seconds
MPU::GMP::fromdigits() took: 0.13911 seconds
MPU::PP::fromdigits() took: 15.063196 seconds
MPU::PP::_FastIntegerInput() took: 2.883047 seconds
```

Obviously in this example, ntheory is using the new GMP code.  It has a small overhead as it starts converting the number before finding it overflows, then calling the GMP routine, then turning the result into a Math::BigInt.

The PP::fromdigits is the old simple quadratic code, while PP::_FastIntegerInput() is your code plugged in.  The speed difference is using the generic mulint vs. GMP mulint -- the latter is leaving everything as strings, the former is converting things to Math::BigInt objects.  I'll do more fiddling with the PP code.

**Comment by trizen** [comment]
I confirm the new performance:

```
FastIntegerInput() took: 0.836795 seconds
ntheory::fromdigits() took: 0.112751 seconds
```

Awesome work!

Even though PARI supports arbitrarily large bases:

```pari
fromdigits(digits(100!, 2^128 + 1), 2^128 + 1) == 100!
```

...limiting the base to a native integer should be fine for practical purposes.
