### ISSUE TITLE
[suggestion] Algorithm for checking if n is k-smooth.

### ISSUE THREAD

**Issue by trizen** [danaj/Math-Prime-Util#40]
It would be nice to have a new method, called `is_smooth(n,k)`, returning true iff n is k-smooth.

I propose the following algorithm:

```perl
use 5.020;
use warnings;

use Math::GMPz;
use Math::Prime::Util::GMP qw(factor powint subint);

sub is_smooth {
    my ($n, $k) = @_;

    if (ref($n) ne 'Math::GMPz') {
        $n = Math::GMPz->new("$n");
    }

    return 0 if Math::GMPz::Rmpz_sgn($n) <= 0;
    return 0 if $k <= 0;
    return 1 if Math::GMPz::Rmpz_cmp_ui($n, 1) == 0;

    state %cache;

    # Clear the cache when there too many values stored
    if (scalar(keys %cache) > 100) {    # or whatever value
        Math::GMPz::Rmpz_clear($_) for values %cache;
        undef %cache;
    }

    my $B = (
        $cache{$k} //= do {
            my $t = Math::GMPz::Rmpz_init_nobless();
            Math::GMPz::Rmpz_primorial_ui($t, $k);
            $t;
        }
    );

    my $g = Math::GMPz::Rmpz_init();
    my $t = Math::GMPz::Rmpz_init_set($n);

    Math::GMPz::Rmpz_gcd($g, $t, $B);

    while (Math::GMPz::Rmpz_cmp_ui($g, 1) > 0) {
        Math::GMPz::Rmpz_remove($t, $t, $g);
        return 1 if (Math::GMPz::Rmpz_cmp_ui($t, 1) == 0);
        Math::GMPz::Rmpz_gcd($g, $t, $g);
    }

    return 0;
}

sub is_smooth_slow {
    my ($n, $k) = @_;
    ((factor($n))[-1] // 1) <= $k;
}

local $| = 1;

for my $n(1..150) {
    if (is_smooth(subint(powint(2, $n), 1), 1e6)) {
        print("$n, ");
    }
}

say '';

for my $n(1..150) {
    if (is_smooth_slow(subint(powint(2, $n), 1), 1e6)) {
        print("$n, ");
    }
}

say '';
```

Function `is_smooth(n, k)` is fast when is used for various numbers `n` with fixed `k`.

**Comment by danaj** [comment]
You're right.  There are some internal functions that would work pretty well for this, even if not ideal.  But there's no way to call them from Perl.

I wonder about something analogous with is_rough.

For 64-bit this hasn't really been an issue since factoring is quite fast.  But for bigints, we certainly don't want to be factoring anything if we don't have to.

**Comment by danaj** [comment]
I just checked in is_smooth and is_rough for native ints, with basic support for bigints.  It seems to be 2-10x faster for native values.  With GMP it's faster by using the trial_factor function, but not as fast as the code you have.  I'll write GMP versions soon.

**Comment by trizen** [comment]
Great work! Thank you very much! :+1:
