### ISSUE TITLE
[suggestion] New functions for powerful numbers.

### ISSUE THREAD

**Issue by trizen** [danaj/Math-Prime-Util#41]
A positive integer `n` is called a k-powerful number, if `p^k` divides `n` for every prime `p` dividing `n`.

OEIS sequences:
*   https://oeis.org/A001694 -- 2-powerful numbers
*   https://oeis.org/A036966 -- 3-powerful numbers
*   https://oeis.org/A036967 -- 4-powerful numbers
*   https://oeis.org/A069492 -- 5-powerful numbers
*   https://oeis.org/A069493 -- 6-powerful numbers

k-powerful numbers also have the following form:

```
   2-powerful = a^2 * b^3,             for a,b >= 1
   3-powerful = a^3 * b^4 * c^5,       for a,b,c >= 1
   4-powerful = a^4 * b^5 * c^6 * d^7, for a,b,c,d >= 1
   ...
   k-powerful = a^k * b^(k+1) * c^(k+2) *...* ω^(2*k-1), for a,b,c,...,ω >= 1
```

This allows us to generate them quite efficiently:

```perl
use 5.020;
use warnings;

use ntheory qw(:all);
use experimental qw(signatures);

sub powerful_numbers ($n, $k = 2) {   # returns all the k-powerful numbers <= n

    my @powerful;

    sub ($m, $r) {

        if ($r < $k) {
            push @powerful, $m;
            return;
        }

        foreach my $v (1 .. rootint(divint($n, $m), $r)) {

            if ($r > $k) {
                gcd($m, $v) == 1   or next;
                is_square_free($v) or next;
            }

            __SUB__->(mulint($m, powint($v, $r)), $r - 1);
        }

    }->(1, 2 * $k - 1);

    sort { $a <=> $b } @powerful;
}

foreach my $k (1 .. 10) {
    printf("%2d-powerful: %s, ...\n", $k, join(", ", powerful_numbers(5**$k, $k)));
}
```

...and also to count the number of k-powerful numbers <= n:

```perl
use 5.020;
use warnings;

use ntheory qw(:all);
use experimental qw(signatures);

sub powerful_count ($n, $k = 2) {

    my $count = 0;

    sub ($m, $r) {

        if ($r <= $k) {
            $count += rootint(divint($n, $m), $r);
            return;
        }

        foreach my $v (1 .. rootint(divint($n, $m), $r)) {

            gcd($m, $v) == 1   or next;
            is_square_free($v) or next;

            __SUB__->(mulint($m, powint($v, $r)), $r - 1);
        }
    }->(1, 2 * $k - 1);

    return $count;
}

foreach my $k (2 .. 10) {
    printf("Number of %2d-powerful <= 10^j: {%s}\n", $k,
           join(', ', map { powerful_count(powint(10, $_), $k) } 0 .. ($k + 15)));
}
```

I would like to suggest the following new functions:

```
is_powerful(n,k=2)      -- return 1 if n is k-powerful
powerful_count(n,k=2)   -- count of k-powerful numbers <= n
```

Optionally:

```
powerful(n,k=2)  -- array of k-powerful numbers <= n.
```

See also: 

* https://en.wikipedia.org/wiki/Powerful_number
* [THE DISTRIBUTION OF CUBE-FULL NUMBERS](https://www.cambridge.org/core/journals/glasgow-mathematical-journal/article/distribution-of-cubefull-numbers/3ABFFD38026AAA654392D87FACB82762)

**Comment by danaj** [comment]
is_powerful(n,k) just checked in.  A version in GMP would be nice.  The PP code does try to speed things up a bit, but all-GMP would help, and reduce the times we need to go to full factoring.

10.9s  sum(1,1000000,ispowerful(2^35+i))  # GP
3.96s  $s += ispowerful(2**35+$_) for 1..1000000; say $s;  # using sub
1.05s  mpu '$s += is_powerful(2**35+$_) for 1..1000000; say $s;  # using C with full factoring
0.62s  mpu '$s += is_powerful(2**35+$_) for 1..1000000; say $s;  # using C with trial to n^(1/4)

It looks like Pari/GP is doing trial division also, but is just checking at the end for a perfect square or p checked to n^(1/3).  It's possible to do better.  We only need to look to n^(1/(2k)) so it's even better for higher k.

With bignums it's a bit harder comparison.

**Comment by danaj** [comment]
powerful_count(n,k) and nth_powerful(n,k) just checked in.

For the count, the C code seems decently fast.  It does a quick construction of an is-square-free arrray so skips all the calls to is_square_free, and has a few small optimizations.  The PP code doesn't have those.  I think a GMP version would help.

nth_powerful works, and isn't bad for single calls in the C code, but it isn't blazing fast.  We wouldn't want to get the first million powerful numbers using it (it's ~15 seconds just to get the first 100k), which is disappointing.  But it exists as a first cut.  The PP code works also but is even slower.  With the current approach, GMP won't help.
