### ISSUE TITLE
Memory leak in inverse_totient()

### ISSUE THREAD

**Issue by trizen** [danaj/Math-Prime-Util#45]
There seems to be a memory leak in `inverse_totient(n)` when called in list context:

```perl
use ntheory qw(inverse_totient);

foreach my $n (1..1e8) {
    my @arr = inverse_totient($n);
}
```

After about 10 seconds, the above code ends up using 2+ GB of RAM.

**Comment by danaj** [comment]
Should be fixed in master now.  **Thank you** for reporting!

**Comment by trizen** [comment]
Thank you very much! I confirm the fix.
