### ISSUE TITLE
Segmentation fault inside `forprimes { }`

### ISSUE THREAD

**Issue by trizen** [danaj/Math-Prime-Util#66]
There seems to be a segmentation fault in `forprimes { }` related to allocation of memory. Probably a Perl bug?

Example ([Try it online!](https://tio.run/##K0gtyjH9/7@0OFXBVM/A0MCaC8TMK8lIzS@qVCgs17BKzMnRtObiSssvKijKzE0tVqjmUlAoTqxUUAooyk9OLS7OzEu3UihQsFVQiVeyBsrlVio4pAC5KZllmcX5RcUaZiYWQGSgoKWgoRKva6gJNK5WwUhHAWTb//8A)):

```perl
use 5.010;
use ntheory qw(:all);

forprimes {
  say "Processing: p = $_";
  my @d = divisors(6486480 * ($_-1));
} 2, 10;
```

Fails with:

```
Processing: p = 2
[1]    40563 segmentation fault (core dumped)  perl u.pl
```

Same segmentation fault happens even if we move the work to a separate function ([Try it online!](https://tio.run/##NY5RCsIwEET/c4ql5CMVlVSsSIPQI3iDUm3UYNvEXWsJ4tljKnXZj2VmmLdOY5uHMJCGfC0zqdh09s@btujhMYqibttUMUbDCRpbjRbv8GYQp/MguEvhAGWlfgrVHpIj2rMmMv21ABdN7hL1z5dNFBrzMmSRxG67jythMfWssjRiPoxdLDo0naYZM0MFryYfNkuIX4bwBQ)):

```perl
use 5.010;
use ntheory qw(:all);

sub do_work {
    my ($p) = @_;
    say "Processing: p = $p";
    my @d = divisors(6486480 * ($p-1));
}

forprimes {
    do_work($_);
} 2, 10;
```

Note that other block-functions, such as `forcomposites` and `forsquarefree`, do not have this issue.

**Comment by danaj** [comment]
Can replicate.  Seems to happen as soon as divisors tries to extend the stack.  We get the same segfault if we call the PP routine from XS, and also if we call PP::divisors in the main program.

We don't get the issue with forcomposites ... **but**, we do if we don't use multicall.  If we remove the non-multicall section for primes 2/3/5 in forprimes, everything works for this example.

By moving the 2/3/5 code into multicall, we can avoid this on most platforms.  However that still leaves some weird stuff happening in the non-multicall code, albeit very few platforms actually would use that.
