### ISSUE TITLE
[github version] C implementation of `omega_prime_count(k,n)` is slower than the PP version

### ISSUE THREAD

**Issue by trizen** [danaj/Math-Prime-Util#72]
For some inputs, the C implementation of `omega_prime_count(k,n)` seems to be slower than the PP version implementation. 

Maybe there is a bug somewhere?

Example:

```perl
use 5.014;
use Math::Prime::Util qw();
use Math::Prime::Util::PP qw();
use Time::HiRes qw(gettimeofday tv_interval);

my $t0 = [gettimeofday];
say Math::Prime::Util::omega_prime_count(15, 1922334673882737115);
say "C version took: ", tv_interval($t0, [gettimeofday]);

my $t1 = [gettimeofday];
say Math::Prime::Util::PP::omega_prime_count(15, 1922334673882737115);
say "PP version took: ", tv_interval($t1, [gettimeofday]);
```

Output:

```
365
C version took: 0.745433
365
PP version took: 0.016417
```

**Comment by danaj** [comment]
Can replicate.

The C version is generating primes to sqrt(n), 1386482842 in this example.  This is trying to save time rather than calling next_prime a zillion times.  However, this is far more than are used.

I adjusted for larger k.

**Comment by danaj** [comment]
This is resolved, but I'm not 100% sure we don't overflow the generated primes.  So the todo has an item to look further into this code.  There is a more naive version of the code that has no issues, but it's slower.
